### ISSUE TITLE
How to modify farbric.mod.json to make the mod work on 1.17.0?

### ISSUE THREAD

**Issue by ghost** [aria1th/litematica-printer#53]

**Comment by aria1th** [comment]
@initial62 The most recent version (https://modrinth.com/mod/litematica-printer-easyplace-extension/versions) or artifacts have 1.17.x version support, so you don't have to modify it.

**Comment by ghost** [comment]
Tried this but I get this error: 

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'int net.minecraft.class_2653.method_37439()'

I also tried removing all my other mods except the required ones.

Crash Report:

java.lang.NoSuchMethodError: 'int net.minecraft.class_2653.method_37439()'
	at net.minecraft.class_634.handler$zig000$litematica_printer$onUpdateSlots(class_634.java:5384)
	at net.minecraft.class_634.method_11109(class_634.java)
	at net.minecraft.class_2653.method_11451(class_2653.java:37)
	at net.minecraft.class_2653.method_11054(class_2653.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.class_310.method_1523(class_310.java:1077)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Here's the full one if you need it: 

(https://github.com/aria1th/litematica-printer/files/11232362/crash-2023-04-14_07.42.01-client.txt)

**Comment by aria1th** [comment]
@initial62 1.17 seems like to have another minor mapping differences and bugs which was not fixed in original litematica, so I can't reliably port the version to 1.17.0.

Instead, you can try multiconnect with 1.17.1( or newer) version of clients.

https://github.com/Earthcomputer/multiconnect/releases/tag/v1.4.17

**Comment by ghost** [comment]
Alright thank you.
